# The name of your Flutter project
name: matrix

# A brief description of your Flutter project
description: A new Flutter project.

# This line prevents the package from being accidentally published to pub.dev
# using `flutter pub publish`. Useful for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning information for your application
version: 1.0.0+1

# Minimum required Flutter SDK version
environment:
  sdk: '>=3.1.4 <4.0.0'

# Dependencies specify other packages that your package needs to work
dependencies:
  flutter:
    sdk: flutter
  provider:  # For state management
  firebase_core: ^1.10.6 # For Firebase initialization
  cloud_firestore: ^3.2.2 # For Cloud Firestore
  google_maps_flutter: ^2.1.1 # For Google Maps
  firebase_auth: ^3.11.2 # For authentication
  # Add other dependencies as needed


# Development dependencies for testing
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Flutter-specific configurations
flutter:
  # Ensures that the Material Icons font is included with your application
  uses-material-design: true

  # Optional: Assets to be included in your application
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Optional: Fonts section for custom fonts in your application
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
